# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2865710e0616e7ff76acd8c840d61ea0dd35348c592b0cd89dcfb7c426eb1715d9b041d88f41add2d89db6ce3ce39be87e884d50eb164f219fec76546fcf8731

test:
  secret_key_base: 49cb4a6d493229d8e2ccfb2e5dfd0cb8742f0dca805d7995d6d6fc9e259373a0a7d528c87958a5facef7bb5e73dfe03314b7218b81dae7706261388376400e51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
